import { App, Vault } from '@/core/App';
import { NextraConfig, ExportNode } from './types';
import { ScaffoldEngine } from './ScaffoldEngine';
import { DepthGuard } from './DepthGuard';
import { AssetMapping } from './AssetTransformer';

export class ExportService {
  private app: App;
  private engine: ScaffoldEngine;

  constructor(app: App, config: NextraConfig) {
    this.app = app;
    this.engine = new ScaffoldEngine(config);
  }

  /**
   * Performs the full export of a directory structure to Nextra
   */
  public async export(rootNode: ExportNode): Promise<void> {
    // 1. Initialize scaffold
    await this.engine.initScaffold();

    // 2. Recursive traversal and transformation
    await this.traverse(rootNode, 0, '');

    // 3. Ensure index.md exists at root to avoid 404
    await this.ensureIndexExists(rootNode);

    // 4. Export ZIP
    await this.engine.exportAsZip(`${rootNode.name}-nextra-export.zip`);
  }

  private async ensureIndexExists(rootNode: ExportNode): Promise<void> {
    const zip = this.engine.getZipInstance();
    const hasIndex = zip.file('pages/index.md') || zip.file('pages/index.mdx') || zip.file('pages/index.tsx');
    
    if (!hasIndex) {
      const defaultContent = `# Introduction\n\nWelcome to **${rootNode.name}** documentation.\n\nThis site was generated by Mark Explorer.`;
      zip.file('pages/index.md', defaultContent);
      
      // Update root _meta.js to include index if needed (usually Nextra handles it, but let's be safe)
    }
  }

  private async traverse(
    node: ExportNode, 
    depth: number, 
    relativeDir: string
  ): Promise<void> {
    // Check Depth Guard
    if (!DepthGuard.isAllowed(depth)) {
      console.warn(`Skipping deep directory: ${node.name} at depth ${depth}`);
      return;
    }

    if (node.kind === 'file') {
      await this.processFile(node, relativeDir);
    } else if (node.kind === 'directory' && node.children) {
      // For the root directory, we don't want to include its name in the path
      // so that its contents appear at the root of the site.
      const isRoot = depth === 0;
      const newRelativeDir = isRoot ? '' : (relativeDir ? `${relativeDir}/${node.name}` : node.name);
      
      if (newRelativeDir) {
        this.engine.getZipInstance().folder(`pages/${newRelativeDir}`);
      }

      // Process children
      for (const child of node.children) {
        await this.traverse(child, depth + 1, newRelativeDir);
      }

      // Add _meta.js for this directory (only for actually exported pages)
      const exportedChildren = node.children.filter(child => {
        if (child.kind === 'directory') return true;
        return child.name.endsWith('.md') || child.name.endsWith('.mdx');
      });
      this.engine.addMetaJson(newRelativeDir, exportedChildren);
    }
  }

  private async processFile(node: ExportNode, relativeDir: string): Promise<void> {
    const isMarkdown = node.name.endsWith('.md') || node.name.endsWith('.mdx');
    const path = node.originalPath || node.path || node.name;

    try {
      if (isMarkdown) {
        const content = await this.app.vault.read(path);
        const assets = await this.engine.transformAndAddMarkdown(node.name, content, relativeDir);
        
        // Handle discovered assets (images)
        await this.collectAssets(assets, path);
      } else {
        // Other files (copy as is if they are not markdown)
        // Note: For now we only copy markdown as main pages. 
        // Other files might be assets or ignored.
      }
    } catch (e) {
      console.error(`Failed to process file: ${path}`, e);
    }
  }

  private async collectAssets(assets: AssetMapping[], markdownPath: string): Promise<void> {
    // Resolve relative assets to absolute paths in the vault
    // This part is tricky because we need to know the base directory of the markdown file.
    const baseDir = markdownPath.substring(0, markdownPath.lastIndexOf('/'));

    for (const asset of assets) {
      try {
        // Resolve path (basic implementation)
        let originalPath = asset.originalPath;
        if (originalPath.startsWith('./')) originalPath = originalPath.substring(2);
        
        const absolutePath = baseDir ? `${baseDir}/${originalPath}` : originalPath;
        
        const data = await this.app.vault.readBinary(absolutePath);
        this.engine.addFile({
          path: asset.targetPath.replace('./', 'pages/'), // Place in pages/img/...
          content: data
        });
      } catch (e) {
        console.warn(`Failed to collect asset: ${asset.originalPath} for ${markdownPath}`, e);
      }
    }
  }
}
