import { NextraConfig } from './types';
import { NEXTRA_VERSIONS, NEXTRA_DEFAULTS } from './NextraConstants';

export class TemplateProvider {
  /**
   * Generates package.json content
   */
  static getPackageJson(config: NextraConfig): string {
    const { title } = config.projectInfo;
    return JSON.stringify({
      "name": "nextra-docs",
      "version": "1.0.0",
      "description": `${title} generated by Mark Explorer`,
      "scripts": {
        "dev": "next dev",
        "build": "next build",
        "start": "next start",
        "lint": "next lint"
      },
      "dependencies": {
        "next": NEXTRA_VERSIONS.NEXT,
        "nextra": NEXTRA_VERSIONS.NEXTRA,
        "nextra-theme-docs": NEXTRA_VERSIONS.THEME_DOCS,
        "react": NEXTRA_VERSIONS.REACT,
        "react-dom": NEXTRA_VERSIONS.REACT_DOM
      }
    }, null, 2);
  }

  /**
   * Generates next.config.mjs content
   */
  static getNextConfig(): string {
    return `import nextra from 'nextra'

const withNextra = nextra({
  theme: 'nextra-theme-docs',
  themeConfig: './theme.config.tsx',
})

export default withNextra()
`;
  }

  /**
   * Generates theme.config.tsx content
   */
  static getThemeConfig(config: NextraConfig): string {
    const { title, github, footer } = config.projectInfo;
    const { h, s } = config.theme.useCustom 
      ? config.theme.customColor 
      : { h: NEXTRA_DEFAULTS.PRIMARY_HUE, s: NEXTRA_DEFAULTS.PRIMARY_SATURATION };

    return `import React from 'react'
import { DocsThemeConfig } from 'nextra-theme-docs'

const config: DocsThemeConfig = {
  logo: <span>${title}</span>,
  project: {
    link: '${github || 'https://github.com/shuding/nextra'}',
  },
  docsRepositoryBase: '${github ? github + '/tree/main' : 'https://github.com/shuding/nextra/tree/main'}',
  footer: {
    content: (
      <span>
        {new Date().getFullYear()} © ${title}. ${footer || NEXTRA_DEFAULTS.FOOTER_TEXT}
      </span>
    )
  },
  primaryHue: ${h},
  primarySaturation: ${s},
}

export default config
`;
  }

  /**
   * Generates tsconfig.json content
   */
  static getTsConfig(): string {
    return JSON.stringify({
      "compilerOptions": {
        "target": "es5",
        "lib": ["dom", "dom.iterable", "esnext"],
        "allowJs": true,
        "skipLibCheck": true,
        "strict": false,
        "forceConsistentCasingInFileNames": true,
        "noEmit": true,
        "esModuleInterop": true,
        "module": "esnext",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "jsx": "preserve",
        "incremental": true,
        "plugins": [
          {
            "name": "next"
          }
        ],
        "paths": {
          "@/*": ["./*"]
        }
      },
      "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      "exclude": ["node_modules"]
    }, null, 2);
  }

  /**
   * Generates pages/_app.tsx content
   */
  static getAppJs(): string {
    return `import React from 'react'
import type { AppProps } from 'next/app'

export default function App({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />
}
`;
  }
}
